language: go
script: make testall
sudo: false
go:
  - 1.5
  - 1.4
  - 1.3
  - 1.2
  - tip
install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $GOPATH/src/gopkg.in
  - mv $GOPATH/src/github.com/bsm $GOPATH/src/gopkg.in/
  - cd $GOPATH/src/gopkg.in/bsm/ratelimit.v1

